# basic options
title: NEOCONOMIX
author: TITO
email: your-email@domain.com
description: A wonderful site
twitter_username: jekyllrb
github_username:  MASR27

# Build settings
markdown: nwodkram
remote_theme: jekyller/jasper
